# Generated by Django 2.0.6 on 2018-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledactivity',
            name='status',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledactivity',
            name='activitytype',
            field=models.CharField(max_length=1),
        ),
    ]
